#!/bin/bash

BASE_SRC_DIR=`pwd`

OPENRESTY_VER="1.0.11.28"
OPENRESTY_INSTALL_DIR="openresty-$OPENRESTY_VER"
OPENRESTY_SRCDIR="ngx_openresty-$OPENRESTY_VER"
OPENRESTY_TARGZ="$OPENRESTY_SRCDIR.tar.gz"


NGINX_SERVER_VER="1.0.15"
NGINX_SERVER_SRCDIR="nginx-$NGINX_SERVER_VER"
NGINX_SERVER_TARGZ="$NGINX_SERVER_SRCDIR.tar.gz"
NGINX_SERVER_INSTALL_DIR="nginx-server-$NGINX_SERVER_VER"

ECHO_NGINX_MOD_VER="0.38rc2"
ECHO_NGINX_MOD_DIR="echo-nginx-module-$ECHO_NGINX_MOD_VER"
ECHO_NGINX_MOD_TARGZ="$ECHO_NGINX_MOD_DIR.tar.gz"

NGX_LUA_MOD_VER="0.5.0rc21"
NGX_LUA_MOD_DIR="ngx_lua-$NGX_LUA_MOD_VER"
NGX_LUA_MOD_TARGZ="$NGX_LUA_MOD_DIR.tar.gz"

REDIS_VER="2.4.7"
REDIS_SRCDIR=redis-$REDIS_VER
REDIS_TARGZ="$REDIS_SRCDIR.tar.gz"
REDIS_INSTALL_DIR="redis-server-$REDIS_VER"

ZLIB_VER="1.2.3"
ZLIB_SRCDIR=zlib-$ZLIB_VER
ZLIB_TARGZ="$ZLIB_SRCDIR-fixed.tar.gz"

PROTOBUFCPP_VER="2.3.0"
PROTOBUFCPP_SRCDIR=protobuf-$PROTOBUFCPP_VER
PROTOBUFCPP_TARGZ="$PROTOBUFCPP_SRCDIR.tar.gz"

PROTOBUFC_VER="0.13"
PROTOBUFC_SRCDIR=protobuf-c-$PROTOBUFC_VER
PROTOBUFC_TARGZ="$PROTOBUFC_SRCDIR.tar.gz"

OPENMQ_VER="4_4"
OPENMQ_SRCDIR=openmq$OPENMQ_VER
OPENMQ_TARGZ="$OPENMQ_SRCDIR-c-source.tar.gz"

HIREDIS_VER="v0.10.1-28-gd5d8843"
HIREDIS_SRCDIR=antirez-hiredis-d5d8843
HIREDIS_TARGZ="antirez-hiredis-$HIREDIS_VER.tar.gz"

CURL_VER="7.24.0"
CURL_SRCDIR=curl-$CURL_VER
CURL_TARGZ="$CURL_SRCDIR.tar.gz"

JSON_VER="0.9"
JSON_SRCDIR=json-c-$JSON_VER
JSON_TARGZ="$JSON_SRCDIR.tar.gz"

MQ_PROXY=$BASE_SRC_DIR/mq_proxy

NGX_DEVEL_KIT_VER="0.2.17"
NGX_DEVEL_KIT_SRCDIR="ngx_devel_kit-$NGX_DEVEL_KIT_VER"

