/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_omae_2dbase_2eproto__INCLUDED
#define PROTOBUF_C_omae_2dbase_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Cm__Omae__Base__Error Cm__Omae__Base__Error;
typedef struct _Cm__Omae__Base__ActionResult Cm__Omae__Base__ActionResult;
typedef struct _Cm__Omae__Base__AppInfo Cm__Omae__Base__AppInfo;
typedef struct _Cm__Omae__Base__Configuration Cm__Omae__Base__Configuration;


/* --- enums --- */

typedef enum _Cm__Omae__Base__ActionResult__Result {
  CM__OMAE__BASE__ACTION_RESULT__RESULT__SUCCEED = 1,
  CM__OMAE__BASE__ACTION_RESULT__RESULT__FAILED = 2,
  CM__OMAE__BASE__ACTION_RESULT__RESULT__REJECT = 3
} Cm__Omae__Base__ActionResult__Result;
typedef enum _Cm__Omae__Base__ApplicationType {
  CM__OMAE__BASE__APPLICATION_TYPE__JAVA = 1,
  CM__OMAE__BASE__APPLICATION_TYPE__PHP = 2
} Cm__Omae__Base__ApplicationType;
typedef enum _Cm__Omae__Base__ServerityLevel {
  CM__OMAE__BASE__SERVERITY_LEVEL__FATAL = 1,
  CM__OMAE__BASE__SERVERITY_LEVEL__ERROR = 2
} Cm__Omae__Base__ServerityLevel;
typedef enum _Cm__Omae__Base__NodeAgentType {
  CM__OMAE__BASE__NODE_AGENT_TYPE__NODE_SHARE = 1,
  CM__OMAE__BASE__NODE_AGENT_TYPE__NODE_SINGLE = 2
} Cm__Omae__Base__NodeAgentType;
typedef enum _Cm__Omae__Base__AppServerType {
  CM__OMAE__BASE__APP_SERVER_TYPE__NODE_JETTY = 1,
  CM__OMAE__BASE__APP_SERVER_TYPE__NODE_TOMCAT = 2
} Cm__Omae__Base__AppServerType;

/* --- messages --- */

struct  _Cm__Omae__Base__Error
{
  ProtobufCMessage base;
  char *error_code;
  protobuf_c_boolean has_level;
  Cm__Omae__Base__ServerityLevel level;
  char *reason;
};
#define CM__OMAE__BASE__ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cm__omae__base__error__descriptor) \
    , NULL, 0,0, NULL }


struct  _Cm__Omae__Base__ActionResult
{
  ProtobufCMessage base;
  Cm__Omae__Base__ActionResult__Result result;
  size_t n_error;
  Cm__Omae__Base__Error **error;
};
#define CM__OMAE__BASE__ACTION_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cm__omae__base__action_result__descriptor) \
    , 0, 0,NULL }


struct  _Cm__Omae__Base__AppInfo
{
  ProtobufCMessage base;
  char *id;
  char *version;
  char *sub_version;
  char *quota;
};
#define CM__OMAE__BASE__APP_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cm__omae__base__app_info__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _Cm__Omae__Base__Configuration
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define CM__OMAE__BASE__CONFIGURATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cm__omae__base__configuration__descriptor) \
    , NULL, NULL }


/* Cm__Omae__Base__Error methods */
void   cm__omae__base__error__init
                     (Cm__Omae__Base__Error         *message);
size_t cm__omae__base__error__get_packed_size
                     (const Cm__Omae__Base__Error   *message);
size_t cm__omae__base__error__pack
                     (const Cm__Omae__Base__Error   *message,
                      uint8_t             *out);
size_t cm__omae__base__error__pack_to_buffer
                     (const Cm__Omae__Base__Error   *message,
                      ProtobufCBuffer     *buffer);
Cm__Omae__Base__Error *
       cm__omae__base__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cm__omae__base__error__free_unpacked
                     (Cm__Omae__Base__Error *message,
                      ProtobufCAllocator *allocator);
/* Cm__Omae__Base__ActionResult methods */
void   cm__omae__base__action_result__init
                     (Cm__Omae__Base__ActionResult         *message);
size_t cm__omae__base__action_result__get_packed_size
                     (const Cm__Omae__Base__ActionResult   *message);
size_t cm__omae__base__action_result__pack
                     (const Cm__Omae__Base__ActionResult   *message,
                      uint8_t             *out);
size_t cm__omae__base__action_result__pack_to_buffer
                     (const Cm__Omae__Base__ActionResult   *message,
                      ProtobufCBuffer     *buffer);
Cm__Omae__Base__ActionResult *
       cm__omae__base__action_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cm__omae__base__action_result__free_unpacked
                     (Cm__Omae__Base__ActionResult *message,
                      ProtobufCAllocator *allocator);
/* Cm__Omae__Base__AppInfo methods */
void   cm__omae__base__app_info__init
                     (Cm__Omae__Base__AppInfo         *message);
size_t cm__omae__base__app_info__get_packed_size
                     (const Cm__Omae__Base__AppInfo   *message);
size_t cm__omae__base__app_info__pack
                     (const Cm__Omae__Base__AppInfo   *message,
                      uint8_t             *out);
size_t cm__omae__base__app_info__pack_to_buffer
                     (const Cm__Omae__Base__AppInfo   *message,
                      ProtobufCBuffer     *buffer);
Cm__Omae__Base__AppInfo *
       cm__omae__base__app_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cm__omae__base__app_info__free_unpacked
                     (Cm__Omae__Base__AppInfo *message,
                      ProtobufCAllocator *allocator);
/* Cm__Omae__Base__Configuration methods */
void   cm__omae__base__configuration__init
                     (Cm__Omae__Base__Configuration         *message);
size_t cm__omae__base__configuration__get_packed_size
                     (const Cm__Omae__Base__Configuration   *message);
size_t cm__omae__base__configuration__pack
                     (const Cm__Omae__Base__Configuration   *message,
                      uint8_t             *out);
size_t cm__omae__base__configuration__pack_to_buffer
                     (const Cm__Omae__Base__Configuration   *message,
                      ProtobufCBuffer     *buffer);
Cm__Omae__Base__Configuration *
       cm__omae__base__configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cm__omae__base__configuration__free_unpacked
                     (Cm__Omae__Base__Configuration *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Cm__Omae__Base__Error_Closure)
                 (const Cm__Omae__Base__Error *message,
                  void *closure_data);
typedef void (*Cm__Omae__Base__ActionResult_Closure)
                 (const Cm__Omae__Base__ActionResult *message,
                  void *closure_data);
typedef void (*Cm__Omae__Base__AppInfo_Closure)
                 (const Cm__Omae__Base__AppInfo *message,
                  void *closure_data);
typedef void (*Cm__Omae__Base__Configuration_Closure)
                 (const Cm__Omae__Base__Configuration *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    cm__omae__base__application_type__descriptor;
extern const ProtobufCEnumDescriptor    cm__omae__base__serverity_level__descriptor;
extern const ProtobufCEnumDescriptor    cm__omae__base__node_agent_type__descriptor;
extern const ProtobufCEnumDescriptor    cm__omae__base__app_server_type__descriptor;
extern const ProtobufCMessageDescriptor cm__omae__base__error__descriptor;
extern const ProtobufCMessageDescriptor cm__omae__base__action_result__descriptor;
extern const ProtobufCEnumDescriptor    cm__omae__base__action_result__result__descriptor;
extern const ProtobufCMessageDescriptor cm__omae__base__app_info__descriptor;
extern const ProtobufCMessageDescriptor cm__omae__base__configuration__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_omae_2dbase_2eproto__INCLUDED */
