/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_appmaster_2dapprouter_2eproto__INCLUDED
#define PROTOBUF_C_appmaster_2dapprouter_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "omae-base.pb-c.h"

typedef struct _AppRouterJoin AppRouterJoin;
typedef struct _AppRouterJoinResponse AppRouterJoinResponse;
typedef struct _AppRouterQuit AppRouterQuit;
typedef struct _AppRouterQuitResponse AppRouterQuitResponse;
typedef struct _AppRouterHeartBeat AppRouterHeartBeat;
typedef struct _AppRouterMapCommand AppRouterMapCommand;
typedef struct _AppRouterMapCommandResponse AppRouterMapCommandResponse;
typedef struct _AppRouterMapRefresh AppRouterMapRefresh;
typedef struct _AppRouterMapRefreshResponse AppRouterMapRefreshResponse;
typedef struct _UpdateAppRouterConfiguration UpdateAppRouterConfiguration;
typedef struct _UpdateAppRouterConfigurationResponse UpdateAppRouterConfigurationResponse;
typedef struct _AppRouterMap AppRouterMap;
typedef struct _RouterMap RouterMap;
typedef struct _RouterMapCommand RouterMapCommand;


/* --- enums --- */

typedef enum _RouterMapOperation {
  ROUTER_MAP_OPERATION__ADD = 1,
  ROUTER_MAP_OPERATION__DELETE = 2
} RouterMapOperation;

/* --- messages --- */

struct  _AppRouterJoin
{
  ProtobufCMessage base;
  char *request_id;
  char *app_router_id;
  char *session_id;
};
#define APP_ROUTER_JOIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_join__descriptor) \
    , NULL, NULL, NULL }


struct  _AppRouterJoinResponse
{
  ProtobufCMessage base;
  Cm__Omae__Base__ActionResult *action_result;
  char *request_id;
  char *session_id;
  size_t n_app_router_map;
  AppRouterMap **app_router_map;
  size_t n_configuration;
  Cm__Omae__Base__Configuration **configuration;
};
#define APP_ROUTER_JOIN_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_join_response__descriptor) \
    , NULL, NULL, NULL, 0,NULL, 0,NULL }


struct  _AppRouterQuit
{
  ProtobufCMessage base;
  char *request_id;
  char *app_router_id;
  char *session_id;
};
#define APP_ROUTER_QUIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_quit__descriptor) \
    , NULL, NULL, NULL }


struct  _AppRouterQuitResponse
{
  ProtobufCMessage base;
  Cm__Omae__Base__ActionResult *action_result;
  char *request_id;
  char *session_id;
};
#define APP_ROUTER_QUIT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_quit_response__descriptor) \
    , NULL, NULL, NULL }


struct  _AppRouterHeartBeat
{
  ProtobufCMessage base;
  char *app_router_id;
  char *session_id;
  uint64_t timestamp;
};
#define APP_ROUTER_HEART_BEAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_heart_beat__descriptor) \
    , NULL, NULL, 0 }


struct  _AppRouterMapCommand
{
  ProtobufCMessage base;
  char *request_id;
  Cm__Omae__Base__AppInfo *appinfo;
  size_t n_router_map_command;
  RouterMapCommand **router_map_command;
};
#define APP_ROUTER_MAP_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_map_command__descriptor) \
    , NULL, NULL, 0,NULL }


struct  _AppRouterMapCommandResponse
{
  ProtobufCMessage base;
  Cm__Omae__Base__ActionResult *action_result;
  char *request_id;
  char *app_router_id;
  char *session_id;
};
#define APP_ROUTER_MAP_COMMAND_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_map_command_response__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _AppRouterMapRefresh
{
  ProtobufCMessage base;
  char *request_id;
  size_t n_app_router_map;
  AppRouterMap **app_router_map;
};
#define APP_ROUTER_MAP_REFRESH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_map_refresh__descriptor) \
    , NULL, 0,NULL }


struct  _AppRouterMapRefreshResponse
{
  ProtobufCMessage base;
  Cm__Omae__Base__ActionResult *action_result;
  char *request_id;
  char *app_router_id;
  char *session_id;
};
#define APP_ROUTER_MAP_REFRESH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_map_refresh_response__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _UpdateAppRouterConfiguration
{
  ProtobufCMessage base;
  char *request_id;
  Cm__Omae__Base__Configuration *configuration;
};
#define UPDATE_APP_ROUTER_CONFIGURATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&update_app_router_configuration__descriptor) \
    , NULL, NULL }


struct  _UpdateAppRouterConfigurationResponse
{
  ProtobufCMessage base;
  Cm__Omae__Base__ActionResult *action_result;
  char *request_id;
  char *app_router_id;
  char *session_id;
};
#define UPDATE_APP_ROUTER_CONFIGURATION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&update_app_router_configuration_response__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _AppRouterMap
{
  ProtobufCMessage base;
  Cm__Omae__Base__AppInfo *app_info;
  size_t n_router_map;
  RouterMap **router_map;
};
#define APP_ROUTER_MAP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_router_map__descriptor) \
    , NULL, 0,NULL }


struct  _RouterMap
{
  ProtobufCMessage base;
  size_t n_domain_name;
  char **domain_name;
  size_t n_destination;
  char **destination;
};
#define ROUTER_MAP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&router_map__descriptor) \
    , 0,NULL, 0,NULL }


struct  _RouterMapCommand
{
  ProtobufCMessage base;
  RouterMapOperation operation;
  RouterMap *router_map;
};
#define ROUTER_MAP_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&router_map_command__descriptor) \
    , 0, NULL }


/* AppRouterJoin methods */
void   app_router_join__init
                     (AppRouterJoin         *message);
size_t app_router_join__get_packed_size
                     (const AppRouterJoin   *message);
size_t app_router_join__pack
                     (const AppRouterJoin   *message,
                      uint8_t             *out);
size_t app_router_join__pack_to_buffer
                     (const AppRouterJoin   *message,
                      ProtobufCBuffer     *buffer);
AppRouterJoin *
       app_router_join__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_join__free_unpacked
                     (AppRouterJoin *message,
                      ProtobufCAllocator *allocator);
/* AppRouterJoinResponse methods */
void   app_router_join_response__init
                     (AppRouterJoinResponse         *message);
size_t app_router_join_response__get_packed_size
                     (const AppRouterJoinResponse   *message);
size_t app_router_join_response__pack
                     (const AppRouterJoinResponse   *message,
                      uint8_t             *out);
size_t app_router_join_response__pack_to_buffer
                     (const AppRouterJoinResponse   *message,
                      ProtobufCBuffer     *buffer);
AppRouterJoinResponse *
       app_router_join_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_join_response__free_unpacked
                     (AppRouterJoinResponse *message,
                      ProtobufCAllocator *allocator);
/* AppRouterQuit methods */
void   app_router_quit__init
                     (AppRouterQuit         *message);
size_t app_router_quit__get_packed_size
                     (const AppRouterQuit   *message);
size_t app_router_quit__pack
                     (const AppRouterQuit   *message,
                      uint8_t             *out);
size_t app_router_quit__pack_to_buffer
                     (const AppRouterQuit   *message,
                      ProtobufCBuffer     *buffer);
AppRouterQuit *
       app_router_quit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_quit__free_unpacked
                     (AppRouterQuit *message,
                      ProtobufCAllocator *allocator);
/* AppRouterQuitResponse methods */
void   app_router_quit_response__init
                     (AppRouterQuitResponse         *message);
size_t app_router_quit_response__get_packed_size
                     (const AppRouterQuitResponse   *message);
size_t app_router_quit_response__pack
                     (const AppRouterQuitResponse   *message,
                      uint8_t             *out);
size_t app_router_quit_response__pack_to_buffer
                     (const AppRouterQuitResponse   *message,
                      ProtobufCBuffer     *buffer);
AppRouterQuitResponse *
       app_router_quit_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_quit_response__free_unpacked
                     (AppRouterQuitResponse *message,
                      ProtobufCAllocator *allocator);
/* AppRouterHeartBeat methods */
void   app_router_heart_beat__init
                     (AppRouterHeartBeat         *message);
size_t app_router_heart_beat__get_packed_size
                     (const AppRouterHeartBeat   *message);
size_t app_router_heart_beat__pack
                     (const AppRouterHeartBeat   *message,
                      uint8_t             *out);
size_t app_router_heart_beat__pack_to_buffer
                     (const AppRouterHeartBeat   *message,
                      ProtobufCBuffer     *buffer);
AppRouterHeartBeat *
       app_router_heart_beat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_heart_beat__free_unpacked
                     (AppRouterHeartBeat *message,
                      ProtobufCAllocator *allocator);
/* AppRouterMapCommand methods */
void   app_router_map_command__init
                     (AppRouterMapCommand         *message);
size_t app_router_map_command__get_packed_size
                     (const AppRouterMapCommand   *message);
size_t app_router_map_command__pack
                     (const AppRouterMapCommand   *message,
                      uint8_t             *out);
size_t app_router_map_command__pack_to_buffer
                     (const AppRouterMapCommand   *message,
                      ProtobufCBuffer     *buffer);
AppRouterMapCommand *
       app_router_map_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_map_command__free_unpacked
                     (AppRouterMapCommand *message,
                      ProtobufCAllocator *allocator);
/* AppRouterMapCommandResponse methods */
void   app_router_map_command_response__init
                     (AppRouterMapCommandResponse         *message);
size_t app_router_map_command_response__get_packed_size
                     (const AppRouterMapCommandResponse   *message);
size_t app_router_map_command_response__pack
                     (const AppRouterMapCommandResponse   *message,
                      uint8_t             *out);
size_t app_router_map_command_response__pack_to_buffer
                     (const AppRouterMapCommandResponse   *message,
                      ProtobufCBuffer     *buffer);
AppRouterMapCommandResponse *
       app_router_map_command_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_map_command_response__free_unpacked
                     (AppRouterMapCommandResponse *message,
                      ProtobufCAllocator *allocator);
/* AppRouterMapRefresh methods */
void   app_router_map_refresh__init
                     (AppRouterMapRefresh         *message);
size_t app_router_map_refresh__get_packed_size
                     (const AppRouterMapRefresh   *message);
size_t app_router_map_refresh__pack
                     (const AppRouterMapRefresh   *message,
                      uint8_t             *out);
size_t app_router_map_refresh__pack_to_buffer
                     (const AppRouterMapRefresh   *message,
                      ProtobufCBuffer     *buffer);
AppRouterMapRefresh *
       app_router_map_refresh__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_map_refresh__free_unpacked
                     (AppRouterMapRefresh *message,
                      ProtobufCAllocator *allocator);
/* AppRouterMapRefreshResponse methods */
void   app_router_map_refresh_response__init
                     (AppRouterMapRefreshResponse         *message);
size_t app_router_map_refresh_response__get_packed_size
                     (const AppRouterMapRefreshResponse   *message);
size_t app_router_map_refresh_response__pack
                     (const AppRouterMapRefreshResponse   *message,
                      uint8_t             *out);
size_t app_router_map_refresh_response__pack_to_buffer
                     (const AppRouterMapRefreshResponse   *message,
                      ProtobufCBuffer     *buffer);
AppRouterMapRefreshResponse *
       app_router_map_refresh_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_map_refresh_response__free_unpacked
                     (AppRouterMapRefreshResponse *message,
                      ProtobufCAllocator *allocator);
/* UpdateAppRouterConfiguration methods */
void   update_app_router_configuration__init
                     (UpdateAppRouterConfiguration         *message);
size_t update_app_router_configuration__get_packed_size
                     (const UpdateAppRouterConfiguration   *message);
size_t update_app_router_configuration__pack
                     (const UpdateAppRouterConfiguration   *message,
                      uint8_t             *out);
size_t update_app_router_configuration__pack_to_buffer
                     (const UpdateAppRouterConfiguration   *message,
                      ProtobufCBuffer     *buffer);
UpdateAppRouterConfiguration *
       update_app_router_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   update_app_router_configuration__free_unpacked
                     (UpdateAppRouterConfiguration *message,
                      ProtobufCAllocator *allocator);
/* UpdateAppRouterConfigurationResponse methods */
void   update_app_router_configuration_response__init
                     (UpdateAppRouterConfigurationResponse         *message);
size_t update_app_router_configuration_response__get_packed_size
                     (const UpdateAppRouterConfigurationResponse   *message);
size_t update_app_router_configuration_response__pack
                     (const UpdateAppRouterConfigurationResponse   *message,
                      uint8_t             *out);
size_t update_app_router_configuration_response__pack_to_buffer
                     (const UpdateAppRouterConfigurationResponse   *message,
                      ProtobufCBuffer     *buffer);
UpdateAppRouterConfigurationResponse *
       update_app_router_configuration_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   update_app_router_configuration_response__free_unpacked
                     (UpdateAppRouterConfigurationResponse *message,
                      ProtobufCAllocator *allocator);
/* AppRouterMap methods */
void   app_router_map__init
                     (AppRouterMap         *message);
size_t app_router_map__get_packed_size
                     (const AppRouterMap   *message);
size_t app_router_map__pack
                     (const AppRouterMap   *message,
                      uint8_t             *out);
size_t app_router_map__pack_to_buffer
                     (const AppRouterMap   *message,
                      ProtobufCBuffer     *buffer);
AppRouterMap *
       app_router_map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_router_map__free_unpacked
                     (AppRouterMap *message,
                      ProtobufCAllocator *allocator);
/* RouterMap methods */
void   router_map__init
                     (RouterMap         *message);
size_t router_map__get_packed_size
                     (const RouterMap   *message);
size_t router_map__pack
                     (const RouterMap   *message,
                      uint8_t             *out);
size_t router_map__pack_to_buffer
                     (const RouterMap   *message,
                      ProtobufCBuffer     *buffer);
RouterMap *
       router_map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   router_map__free_unpacked
                     (RouterMap *message,
                      ProtobufCAllocator *allocator);
/* RouterMapCommand methods */
void   router_map_command__init
                     (RouterMapCommand         *message);
size_t router_map_command__get_packed_size
                     (const RouterMapCommand   *message);
size_t router_map_command__pack
                     (const RouterMapCommand   *message,
                      uint8_t             *out);
size_t router_map_command__pack_to_buffer
                     (const RouterMapCommand   *message,
                      ProtobufCBuffer     *buffer);
RouterMapCommand *
       router_map_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   router_map_command__free_unpacked
                     (RouterMapCommand *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AppRouterJoin_Closure)
                 (const AppRouterJoin *message,
                  void *closure_data);
typedef void (*AppRouterJoinResponse_Closure)
                 (const AppRouterJoinResponse *message,
                  void *closure_data);
typedef void (*AppRouterQuit_Closure)
                 (const AppRouterQuit *message,
                  void *closure_data);
typedef void (*AppRouterQuitResponse_Closure)
                 (const AppRouterQuitResponse *message,
                  void *closure_data);
typedef void (*AppRouterHeartBeat_Closure)
                 (const AppRouterHeartBeat *message,
                  void *closure_data);
typedef void (*AppRouterMapCommand_Closure)
                 (const AppRouterMapCommand *message,
                  void *closure_data);
typedef void (*AppRouterMapCommandResponse_Closure)
                 (const AppRouterMapCommandResponse *message,
                  void *closure_data);
typedef void (*AppRouterMapRefresh_Closure)
                 (const AppRouterMapRefresh *message,
                  void *closure_data);
typedef void (*AppRouterMapRefreshResponse_Closure)
                 (const AppRouterMapRefreshResponse *message,
                  void *closure_data);
typedef void (*UpdateAppRouterConfiguration_Closure)
                 (const UpdateAppRouterConfiguration *message,
                  void *closure_data);
typedef void (*UpdateAppRouterConfigurationResponse_Closure)
                 (const UpdateAppRouterConfigurationResponse *message,
                  void *closure_data);
typedef void (*AppRouterMap_Closure)
                 (const AppRouterMap *message,
                  void *closure_data);
typedef void (*RouterMap_Closure)
                 (const RouterMap *message,
                  void *closure_data);
typedef void (*RouterMapCommand_Closure)
                 (const RouterMapCommand *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    router_map_operation__descriptor;
extern const ProtobufCMessageDescriptor app_router_join__descriptor;
extern const ProtobufCMessageDescriptor app_router_join_response__descriptor;
extern const ProtobufCMessageDescriptor app_router_quit__descriptor;
extern const ProtobufCMessageDescriptor app_router_quit_response__descriptor;
extern const ProtobufCMessageDescriptor app_router_heart_beat__descriptor;
extern const ProtobufCMessageDescriptor app_router_map_command__descriptor;
extern const ProtobufCMessageDescriptor app_router_map_command_response__descriptor;
extern const ProtobufCMessageDescriptor app_router_map_refresh__descriptor;
extern const ProtobufCMessageDescriptor app_router_map_refresh_response__descriptor;
extern const ProtobufCMessageDescriptor update_app_router_configuration__descriptor;
extern const ProtobufCMessageDescriptor update_app_router_configuration_response__descriptor;
extern const ProtobufCMessageDescriptor app_router_map__descriptor;
extern const ProtobufCMessageDescriptor router_map__descriptor;
extern const ProtobufCMessageDescriptor router_map_command__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_appmaster_2dapprouter_2eproto__INCLUDED */
