/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "omae-base.pb-c.h"
void   cm__omae__base__error__init
                     (Cm__Omae__Base__Error         *message)
{
  static Cm__Omae__Base__Error init_value = CM__OMAE__BASE__ERROR__INIT;
  *message = init_value;
}
size_t cm__omae__base__error__get_packed_size
                     (const Cm__Omae__Base__Error *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cm__omae__base__error__pack
                     (const Cm__Omae__Base__Error *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cm__omae__base__error__pack_to_buffer
                     (const Cm__Omae__Base__Error *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cm__Omae__Base__Error *
       cm__omae__base__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cm__Omae__Base__Error *)
     protobuf_c_message_unpack (&cm__omae__base__error__descriptor,
                                allocator, len, data);
}
void   cm__omae__base__error__free_unpacked
                     (Cm__Omae__Base__Error *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cm__omae__base__action_result__init
                     (Cm__Omae__Base__ActionResult         *message)
{
  static Cm__Omae__Base__ActionResult init_value = CM__OMAE__BASE__ACTION_RESULT__INIT;
  *message = init_value;
}
size_t cm__omae__base__action_result__get_packed_size
                     (const Cm__Omae__Base__ActionResult *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__action_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cm__omae__base__action_result__pack
                     (const Cm__Omae__Base__ActionResult *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__action_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cm__omae__base__action_result__pack_to_buffer
                     (const Cm__Omae__Base__ActionResult *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__action_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cm__Omae__Base__ActionResult *
       cm__omae__base__action_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cm__Omae__Base__ActionResult *)
     protobuf_c_message_unpack (&cm__omae__base__action_result__descriptor,
                                allocator, len, data);
}
void   cm__omae__base__action_result__free_unpacked
                     (Cm__Omae__Base__ActionResult *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__action_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cm__omae__base__app_info__init
                     (Cm__Omae__Base__AppInfo         *message)
{
  static Cm__Omae__Base__AppInfo init_value = CM__OMAE__BASE__APP_INFO__INIT;
  *message = init_value;
}
size_t cm__omae__base__app_info__get_packed_size
                     (const Cm__Omae__Base__AppInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__app_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cm__omae__base__app_info__pack
                     (const Cm__Omae__Base__AppInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__app_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cm__omae__base__app_info__pack_to_buffer
                     (const Cm__Omae__Base__AppInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__app_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cm__Omae__Base__AppInfo *
       cm__omae__base__app_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cm__Omae__Base__AppInfo *)
     protobuf_c_message_unpack (&cm__omae__base__app_info__descriptor,
                                allocator, len, data);
}
void   cm__omae__base__app_info__free_unpacked
                     (Cm__Omae__Base__AppInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__app_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cm__omae__base__configuration__init
                     (Cm__Omae__Base__Configuration         *message)
{
  static Cm__Omae__Base__Configuration init_value = CM__OMAE__BASE__CONFIGURATION__INIT;
  *message = init_value;
}
size_t cm__omae__base__configuration__get_packed_size
                     (const Cm__Omae__Base__Configuration *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cm__omae__base__configuration__pack
                     (const Cm__Omae__Base__Configuration *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cm__omae__base__configuration__pack_to_buffer
                     (const Cm__Omae__Base__Configuration *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cm__Omae__Base__Configuration *
       cm__omae__base__configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cm__Omae__Base__Configuration *)
     protobuf_c_message_unpack (&cm__omae__base__configuration__descriptor,
                                allocator, len, data);
}
void   cm__omae__base__configuration__free_unpacked
                     (Cm__Omae__Base__Configuration *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cm__omae__base__configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cm__omae__base__error__field_descriptors[3] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__Error, error_code),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "level",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__Error, has_level),
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__Error, level),
    &cm__omae__base__serverity_level__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "reason",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__Error, reason),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned cm__omae__base__error__field_indices_by_name[] = {
  0,   /* field[0] = error_code */
  1,   /* field[1] = level */
  2,   /* field[2] = reason */
};
static const ProtobufCIntRange cm__omae__base__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cm__omae__base__error__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cm.omae.base.Error",
  "Error",
  "Cm__Omae__Base__Error",
  "cm.omae.base",
  sizeof(Cm__Omae__Base__Error),
  3,
  cm__omae__base__error__field_descriptors,
  cm__omae__base__error__field_indices_by_name,
  1,  cm__omae__base__error__number_ranges,
  (ProtobufCMessageInit) cm__omae__base__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue cm__omae__base__action_result__result__enum_values_by_number[3] =
{
  { "SUCCEED", "CM__OMAE__BASE__ACTION_RESULT__RESULT__SUCCEED", 1 },
  { "FAILED", "CM__OMAE__BASE__ACTION_RESULT__RESULT__FAILED", 2 },
  { "REJECT", "CM__OMAE__BASE__ACTION_RESULT__RESULT__REJECT", 3 },
};
static const ProtobufCIntRange cm__omae__base__action_result__result__value_ranges[] = {
{1, 0},{0, 3}
};
const ProtobufCEnumValueIndex cm__omae__base__action_result__result__enum_values_by_name[3] =
{
  { "FAILED", 1 },
  { "REJECT", 2 },
  { "SUCCEED", 0 },
};
const ProtobufCEnumDescriptor cm__omae__base__action_result__result__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "cm.omae.base.ActionResult.Result",
  "Result",
  "Cm__Omae__Base__ActionResult__Result",
  "cm.omae.base",
  3,
  cm__omae__base__action_result__result__enum_values_by_number,
  3,
  cm__omae__base__action_result__result__enum_values_by_name,
  1,
  cm__omae__base__action_result__result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor cm__omae__base__action_result__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__ActionResult, result),
    &cm__omae__base__action_result__result__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__ActionResult, n_error),
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__ActionResult, error),
    &cm__omae__base__error__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned cm__omae__base__action_result__field_indices_by_name[] = {
  1,   /* field[1] = error */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange cm__omae__base__action_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cm__omae__base__action_result__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cm.omae.base.ActionResult",
  "ActionResult",
  "Cm__Omae__Base__ActionResult",
  "cm.omae.base",
  sizeof(Cm__Omae__Base__ActionResult),
  2,
  cm__omae__base__action_result__field_descriptors,
  cm__omae__base__action_result__field_indices_by_name,
  1,  cm__omae__base__action_result__number_ranges,
  (ProtobufCMessageInit) cm__omae__base__action_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cm__omae__base__app_info__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__AppInfo, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__AppInfo, version),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "sub_version",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__AppInfo, sub_version),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "quota",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__AppInfo, quota),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned cm__omae__base__app_info__field_indices_by_name[] = {
  0,   /* field[0] = id */
  3,   /* field[3] = quota */
  2,   /* field[2] = sub_version */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange cm__omae__base__app_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cm__omae__base__app_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cm.omae.base.AppInfo",
  "AppInfo",
  "Cm__Omae__Base__AppInfo",
  "cm.omae.base",
  sizeof(Cm__Omae__Base__AppInfo),
  4,
  cm__omae__base__app_info__field_descriptors,
  cm__omae__base__app_info__field_indices_by_name,
  1,  cm__omae__base__app_info__number_ranges,
  (ProtobufCMessageInit) cm__omae__base__app_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cm__omae__base__configuration__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__Configuration, key),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cm__Omae__Base__Configuration, value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned cm__omae__base__configuration__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange cm__omae__base__configuration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cm__omae__base__configuration__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cm.omae.base.Configuration",
  "Configuration",
  "Cm__Omae__Base__Configuration",
  "cm.omae.base",
  sizeof(Cm__Omae__Base__Configuration),
  2,
  cm__omae__base__configuration__field_descriptors,
  cm__omae__base__configuration__field_indices_by_name,
  1,  cm__omae__base__configuration__number_ranges,
  (ProtobufCMessageInit) cm__omae__base__configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue cm__omae__base__application_type__enum_values_by_number[2] =
{
  { "JAVA", "CM__OMAE__BASE__APPLICATION_TYPE__JAVA", 1 },
  { "PHP", "CM__OMAE__BASE__APPLICATION_TYPE__PHP", 2 },
};
static const ProtobufCIntRange cm__omae__base__application_type__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex cm__omae__base__application_type__enum_values_by_name[2] =
{
  { "JAVA", 0 },
  { "PHP", 1 },
};
const ProtobufCEnumDescriptor cm__omae__base__application_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "cm.omae.base.ApplicationType",
  "ApplicationType",
  "Cm__Omae__Base__ApplicationType",
  "cm.omae.base",
  2,
  cm__omae__base__application_type__enum_values_by_number,
  2,
  cm__omae__base__application_type__enum_values_by_name,
  1,
  cm__omae__base__application_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue cm__omae__base__serverity_level__enum_values_by_number[2] =
{
  { "FATAL", "CM__OMAE__BASE__SERVERITY_LEVEL__FATAL", 1 },
  { "ERROR", "CM__OMAE__BASE__SERVERITY_LEVEL__ERROR", 2 },
};
static const ProtobufCIntRange cm__omae__base__serverity_level__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex cm__omae__base__serverity_level__enum_values_by_name[2] =
{
  { "ERROR", 1 },
  { "FATAL", 0 },
};
const ProtobufCEnumDescriptor cm__omae__base__serverity_level__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "cm.omae.base.ServerityLevel",
  "ServerityLevel",
  "Cm__Omae__Base__ServerityLevel",
  "cm.omae.base",
  2,
  cm__omae__base__serverity_level__enum_values_by_number,
  2,
  cm__omae__base__serverity_level__enum_values_by_name,
  1,
  cm__omae__base__serverity_level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue cm__omae__base__node_agent_type__enum_values_by_number[2] =
{
  { "NODE_SHARE", "CM__OMAE__BASE__NODE_AGENT_TYPE__NODE_SHARE", 1 },
  { "NODE_SINGLE", "CM__OMAE__BASE__NODE_AGENT_TYPE__NODE_SINGLE", 2 },
};
static const ProtobufCIntRange cm__omae__base__node_agent_type__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex cm__omae__base__node_agent_type__enum_values_by_name[2] =
{
  { "NODE_SHARE", 0 },
  { "NODE_SINGLE", 1 },
};
const ProtobufCEnumDescriptor cm__omae__base__node_agent_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "cm.omae.base.NodeAgentType",
  "NodeAgentType",
  "Cm__Omae__Base__NodeAgentType",
  "cm.omae.base",
  2,
  cm__omae__base__node_agent_type__enum_values_by_number,
  2,
  cm__omae__base__node_agent_type__enum_values_by_name,
  1,
  cm__omae__base__node_agent_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue cm__omae__base__app_server_type__enum_values_by_number[2] =
{
  { "NODE_JETTY", "CM__OMAE__BASE__APP_SERVER_TYPE__NODE_JETTY", 1 },
  { "NODE_TOMCAT", "CM__OMAE__BASE__APP_SERVER_TYPE__NODE_TOMCAT", 2 },
};
static const ProtobufCIntRange cm__omae__base__app_server_type__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex cm__omae__base__app_server_type__enum_values_by_name[2] =
{
  { "NODE_JETTY", 0 },
  { "NODE_TOMCAT", 1 },
};
const ProtobufCEnumDescriptor cm__omae__base__app_server_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "cm.omae.base.AppServerType",
  "AppServerType",
  "Cm__Omae__Base__AppServerType",
  "cm.omae.base",
  2,
  cm__omae__base__app_server_type__enum_values_by_number,
  2,
  cm__omae__base__app_server_type__enum_values_by_name,
  1,
  cm__omae__base__app_server_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
